debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  
  [entryPoints.http.redirect]
  entryPoint = "https"
  
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

  [entryPoints.traefik]
  address=":8080"
  [entryPoints.traefik.auth]
    [entryPoints.traefik.auth.basic]
      users = ["ApiUser"]

[acme]
email = "YourMail"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
  entryPoint = "http"

[api]
entrypoint="traefik"
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "YourDomain"
watch = true
exposedByDefault = false
